# Generated by Django 3.2.18 on 2023-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
