# Generated by Django 3.2.18 on 2023-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('bakery', 'Bakery'), ('snacks', 'Snacks'), ('health', 'Health'), ('drinks', 'Drinks'), ('fine dining', 'Fine Dining')], default='bakery', max_length=200),
        ),
    ]
