# Generated by Django 3.2.18 on 2023-04-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='snippet',
            field=models.TextField(max_length=100),
        ),
    ]
