# Generated by Django 3.2.18 on 2023-04-07 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='score',
        ),
        migrations.AddField(
            model_name='recipe',
            name='score',
            field=models.ManyToManyField(blank=True, related_name='recipe_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
