# Generated by Django 3.2.18 on 2023-04-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
