# Generated by Django 3.2.18 on 2023-04-22 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_recipe_score',
            field=models.ManyToManyField(blank=True, related_name='user_recipe_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
