# Generated by Django 3.2.18 on 2023-04-15 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20230415_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('bakery', 'Bakery'), ('snacks', 'Snacks'), ('health', 'Health'), ('drinks', 'Drinks'), ('fine-dining', 'Fine Dining')], default='bakery', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='score',
            field=models.ManyToManyField(blank=True, related_name='recipe_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
