# Generated by Django 3.2.18 on 2023-04-15 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20230415_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='score',
            field=models.ManyToManyField(blank=True, editable=False, related_name='recipe_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
