# Generated by Django 3.2.18 on 2023-04-15 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_recipescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipescore',
            name='user',
            field=models.ForeignKey(default='rcadmin', on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='score',
            field=models.ManyToManyField(blank=True, editable=False, related_name='recipe_score', through='recipes.RecipeScore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipescore',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='recipescore',
            unique_together={('recipe', 'user')},
        ),
    ]
