# Generated by Django 3.2.18 on 2023-04-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='content',
        ),
    ]
