# Generated by Django 3.2.18 on 2023-04-15 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_alter_recipescore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipescore',
            name='user',
            field=models.ForeignKey(default=recipes.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
