# Generated by Django 3.2.18 on 2023-08-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20230820_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_1',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_2',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_3',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_4',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_5',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_6',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_7',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_8',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_1',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_2',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_3',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_4',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_5',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_6',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_7',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_8',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
