# Generated by Django 3.2.18 on 2023-08-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230820_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_1',
            field=models.CharField(default='', max_length=200),
        ),
    ]
