# Generated by Django 3.2.18 on 2023-04-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0013_alter_recipescore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipescore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
