# Generated by Django 3.2.18 on 2023-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_ingredients_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_4',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_5',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_6',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_7',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_8',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_1',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_2',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_3',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_4',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_5',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_6',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_7',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions_8',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
