# Generated by Django 3.2.18 on 2023-08-21 20:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20230821_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='mama.81d4bf9d1fad', max_length=255, verbose_name='image'),
        ),
    ]
