# Generated by Django 3.2.18 on 2023-04-15 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0017_alter_recipescore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipescore',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipescore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_score', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
