# Generated by Django 3.2.18 on 2023-04-15 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0018_auto_20230415_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipescore',
            name='id',
            field=models.BigAutoField(auto_created=True, default='rcadmin', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='score',
            field=models.ManyToManyField(blank=True, default=0, editable=False, related_name='recipe_score', through='recipes.RecipeScore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipescore',
            name='recipe',
            field=models.ForeignKey(default='test-recipe', on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipescore',
            name='user',
            field=models.ForeignKey(default=recipes.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
